- name: restart zammad-init
  ansible.builtin.systemd_service:
    name: zammad-init
    state: restarted
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ podman_link_podman_rootless_user }}"

- name: restart zammad-postgresql
  ansible.builtin.systemd_service:
    name: zammad-postgresql
    state: restarted
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ podman_link_podman_rootless_user }}"

- name: restart link.slice
  ansible.builtin.systemd_service:
    name: link.slice
    state: restarted
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ podman_link_podman_rootless_user }}"
